package consts

var (
	DEVELOPMENT = "DEVELOPMENT"

	LOG_LEVEL              = "LOG_LEVEL"
	LOG_JSON               = "LOG_JSON"
	LOG_ADD_CALLER         = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRACE = "LOG_DISABLE_STACKTRACE"
	LOG_COLORIZE_LINE      = "LOG_COLORIZE_LINE"
	LOG_UNESCAPE_MULTILINE = "LOG_UNESCAPE_MULTILINE"
	// DNS Rate Limiting settings
	RATE_LIMIT_ENABLED         = "DNS_RATE_LIMIT_ENABLED"
	RATE_LIMIT_QUERIES_PER_SEC = "DNS_RATE_LIMIT_QUERIES_PER_SEC"
	RATE_LIMIT_BURST           = "DNS_RATE_LIMIT_BURST"

	// HTTP API settings
	HTTP_API_PORT                 = "HTTP_API_PORT"
	HTTP_API_LIVENESS_PROBE_PORT  = "HTTP_API_LIVENESS_PROBE_PORT"
	HTTP_API_READINESS_PROBE_PORT = "HTTP_API_READINESS_PROBE_PORT"
	HTTP_API_CORS_ALLOWED_ORIGINS = "HTTP_API_CORS_ALLOWED_ORIGINS"

	// Authentication / Keycloak settings
	KEYCLOAK_URL            = "KEYCLOAK_URL"
	KEYCLOAK_REALM          = "KEYCLOAK_REALM"
	KEYCLOAK_API_CLIENT_ID  = "KEYCLOAK_API_CLIENT_ID"
	KEYCLOAK_CLI_CLIENT_ID  = "KEYCLOAK_CLI_CLIENT_ID"
	KEYCLOAK_ADMIN_USER     = "KEYCLOAK_ADMIN_USER"
	KEYCLOAK_ADMIN_PASSWORD = "KEYCLOAK_ADMIN_PASSWORD" // #nosec G101 -- This is an environment variable name, not a hardcoded password

	// ArangoDB settings
	ARANGODB_DATABASE_NAME = "ARANGODB_DATABASE_NAME"
	ARANGODB_USERNAME      = "ARANGODB_USERNAME"
	ARANGODB_PASSWORD      = "ARANGODB_ROOT_PASSWORD" // #nosec G101 -- This is an environment variable name, not a hardcoded password
	ARANGODB_HOST          = "ARANGODB_HOST"
	ARANGODB_PORT          = "ARANGODB_PORT"
	ARANGODB_HTTP2_ENABLED = "ARANGODB_HTTP2_ENABLED"
)
